services:
  - type: web
    name: covid-detector
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address=0.0.0.0 --server.port=$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
    disk:
      name: models
      mountPath: /opt/render/project/src/models
      sizeGB: 3